baseURL = "https://gokarna-hugo.netlify.app"
title = "David Dablo"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "David Dablo"
  description = "UC San Diego Student"
  avatarURL = "/images/avatar.jpeg"
  AvatarAltText = "avatar"
  avatarSize = "size-m"
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/daviddablo/"},
    {name = "github", url = "https://github.com/daviddablo"},
    {name = "email", url = "mailto:ddablo@ucsd.edu"}
  ]
  metaKeywords = ["blog", "gokarna", "hugo"]

#  [[menu.main]]
#    name = "Posts"
#    pre = "<span data-feather='book'></span>"
#    url = "/posts/"
#    weight = 2

  [[menu.main]]
    name = "About"
#    pre = "<span data-feather='tag'></span>"
    url = "/about/"
    weight = 3

  [[menu.main]]
    name = "CV"
#    pre = "<span data-feather='tag'></span>"
    url = "https://drive.google.com/file/d/1DUcs4opj9LvtbRGC_md1LxLeSxOLZxmu/view"
    weight = 4

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
